[build-system]
requires = ["setuptools>=61.0", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "self_fourier_shell_correlation"
version = "0.0.1"
authors = [
  { name="Eric J. Verbeke", email="ev9102@princeton.edu" },
  { name="Vicente González Ruiz", email="vicente.gonzalez.ruiz@gmail.com" },
]
description = "Self Fourier shell correlation (https://www.nature.com/articles/s42003-023-05724-y)"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "opencv-python",
    "scipy",
    "shuffling @ git+https://github.com/vicente-gonzalez-ruiz/shuffling",
    "motion_estimation @ git+https://github.com/vicente-gonzalez-ruiz/motion_estimation",
    "self_fourier_shell_correlation @ git+https://github.com/vicente-gonzalez-ruiz/self_fourier_shell_correlation"
]

[project.urls]
"Homepage" = "https://github.com/vicente-gonzalez-ruiz/self_fourier_shell_correlation"
"Bug Tracker" = "https://github.com/vicente-gonzalez-ruiz/self_fourier_shell_correlation/issues"
